### ISSUE TITLE
ERROR 500 when getting statements

### ISSUE THREAD

**Issue by SrarHu** [adlnet/ADL_LRS#373]
hi ,I'm a new user of LRS, and i have some problems when using my loacl LRS please give me a hand.

I have set up nginx, uWSGI and celery, posting statement is prefect but getting statement will get a `ERROR 500`

here is the log:

<pre><code>2015-12-11 15:08:44,929 [INFO] lrs.views: 
Exception while processing: /xapi/statements
2015-12-11 15:08:44,929 [ERROR] lrs.views: could not identify an equality operator for type json
LINE 1: ...t_score_min", "lrs_statement"."result_score_max", "lrs_state...
                                                             ^
Traceback (most recent call last):
  File "./lrs/views.py", line 204, in handle_request
    return processors[path][req_dict['method']](req_dict)
  File "./lrs/utils/req_process.py", line 192, in statements_get
    resp, content_length = process_complex_get(req_dict)
  File "./lrs/utils/req_process.py", line 96, in process_complex_get
    stmt_result = complex_get(param_dict, limit, language, format, attachments)
  File "./lrs/utils/retrieve_statement.py", line 125, in complex_get
    return create_stmt_result(stmtset, stored_param, language, format)
  File "./lrs/utils/retrieve_statement.py", line 143, in create_stmt_result
    stmt_result = '{"statements": [%s], "more": ""}' % ",".join([json.dumps(stmt.full_statement) for stmt in stmt_set.order_by(stored)])
  File "/home/db_owner/dir_LRS/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 118, in _result_iter
    self._fill_cache()
  File "/home/db_owner/dir_LRS/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 875, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/home/db_owner/dir_LRS/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/home/db_owner/dir_LRS/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/db_owner/dir_LRS/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/home/db_owner/dir_LRS/env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/home/db_owner/dir_LRS/env/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 52, in execute
    return self.cursor.execute(query, args)
DatabaseError: could not identify an equality operator for type json
LINE 1: ...t_score_min", "lrs_statement"."result_score_max", "lrs_state...
                                                             ^
</code></pre>

**Comment by ljwolford** [comment]
I think I've seen this before with newer versions of Postgres. What version of Postgres are you running? I believe if it's 9.3 or above it will crash because it is not interoperable with our jsonfield since it's own jsonfield was introduced in that version.

**Comment by SrarHu** [comment]
I use postgres 9.3 in Ubuntu 14.04, it's the default version when apt-get postgres in 14.04. And I tried 9.4 bufore, the same problem.
Which version do you using now?
I think you should noticed the recommended postgresql version in readme.md.

**Comment by ljwolford** [comment]
I'm using postgres 9.1.18, but yes the reasoning for mentioning the ubuntu version in the spec was because ubuntu 12 still grabs the correct version of postgres whereas newer versions of ubuntu don't. hopefully we wil be upgrading the entire LRS stack here soon since everything is severely out of date.
