### ISSUE TITLE
send Statements with xAPI Lab

### ISSUE THREAD

**Issue by DaTebe** [adlnet/ADL_LRS#396]
Hi,

I'm sending statements with the xAPI Lab to the ADL LRS. As response I get:

> POST http://localhost:8000/xapi/statements 500 (Internal Server Error)
> xapiwrapper.min.js:2 There was a problem communicating with the Learning Record Store. ( 500 | [Errno 111] Connection refused )

The statements are correctly stored in the LRS. What am I missing or is it a bug?

Greets Daniel

**Comment by ljwolford** [comment]
There is a 'logs' directory that is created with the LRS. If you look in it there is a lrs.log file that has full stack traces for any exceptions that happen. That should give you a clear idea on what is going wrong.

**Comment by DaTebe** [comment]
I have looked at the log file and deleted everything. Tried to send a statement and got the error. I looked again in the log file, but it was not filled with an error message. 

I will take a look at this tomorrow.

**Comment by DaTebe** [comment]
I looked into the error log file. But it only tells me which files are affected.
Maybe you can tell me why the LRS tells me "Connection refused", but saves every received statement from xAPI Lab perfectly.

```
2016-06-03 09:17:54,474 [INFO] lrs.views: 
Exception while processing: /xapi/statements
2016-06-03 09:17:54,474 [ERROR] lrs.views: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/daniel/Projects/ADL_LRS/lrs/views.py", line 205, in handle_request
    return processors[path][req_dict['method']](req_dict)
  File "/home/daniel/Projects/ADL_LRS/lrs/utils/req_process.py", line 125, in statements_post
    check_activity_metadata.delay(stmt_ids)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/celery/app/task.py", line 560, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/kombu/connection.py", line 457, in _ensured
    interval_max)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/kombu/connection.py", line 742, in connection
    self._connection = self._establish_connection()
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/kombu/connection.py", line 697, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
```

**Comment by ljwolford** [comment]
It looks like your celery tasks are not working. The celery tasks are responsible for retrieving metadata from the activity id, voiding statements, and handling any webhooks. Have a look at this page (https://github.com/adlnet/ADL_LRS/wiki/Using-Celery) to make sure it's up and running.

**Comment by DaTebe** [comment]
That must be it.
Unfortunately I have problems with postgres. I'm not able to create the database lrs.
I was playing around with the LRS and broke it. I re-installed everything and now I'm a little bit puzzled.

**Comment by ljwolford** [comment]
Were you able to get it working again? What issues are you having?

**Comment by DaTebe** [comment]
Currently I'm not at home. But as far as I remember it was something like this:
"Could not find database lrs"

I tried to create the database with your instructions given in the install guide. But it does not work. The error is thrown when I execute the command `fab setup_env`

I can hand further information later when I'm at home.

**Comment by DaTebe** [comment]
This is the error log I'm reveiving from the `fab setup_env` command.
```
(env) daniel@daniel-UX305FA:~/Projects/ADL_LRS$ fab setup_lrs
[localhost] local: ./manage.py createcachetable
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/django/core/management/commands/createcachetable.py", line 41, in handle
    self.create_table(db, cache._table, dry_run)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/django/core/management/commands/createcachetable.py", line 49, in create_table
    if tablename in connection.introspection.table_names():
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/django/db/backends/base/introspection.py", line 56, in table_names
    with self.connection.cursor() as cursor:
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 175, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/daniel/Projects/env/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  database "lrs" does not exist


Fatal error: local() encountered an error (return code 1) while executing './manage.py createcachetable'

Aborting.
```

I tried to create the Database with `CREATE DATABASE lrs OWNER myuser`. I'm not familiar with postgres. `\list` returns 3 Databases `postgres`, `template0` and `template1`.

Any idea about this?

**Comment by ljwolford** [comment]
Hmmm when you open the postgres shell were you using template1 like this:
`sudo -u postgres psql template1`

Once inside you can then run the 'CREATE DATABASE' command. Not sure why it wouldn't be creating it...you should get a 'CREATE DATABASE' response from postgres after you create it.

**Comment by DaTebe** [comment]
Well!
I'm very sorry. I just missed the `;` at the end of the create statement... now it works just fine. Would be much easier if Postgres would throw a `wrong sql sytax error` or something like that. But the response was empty.

Now I will try the celery task thing =)

**Comment by fugu13** [comment]
@DaTebe yeah, I've seen that bite a number of people. Postgres does a very good job with syntax errors... but SQL allows multiline statements, and until there's a semicolon, you haven't ended the statement

**Comment by DaTebe** [comment]
@fugu13
At least I learned something!

**Comment by ljwolford** [comment]
@DaTebe 
The post save signal that we have hooked up does not work when django creates the superuser for some reason. Anytime you create a system user through the UI, it will automatically create and associate an Agent with it.
