### ISSUE TITLE
SyntaxError when type fab setup_lrs

### ISSUE THREAD

**Issue by Yuxin92** [adlnet/ADL_LRS#418]
I'm on fab setup_lrs step, I followed every step, but when comes with fab setup_lrs, it shows "SyntaxError: invalid syntax". I'm in the right path. Code on my computer is 

(env) -sh-4.1$ fab setup_lrs
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/fabric/main.py", line 745, in main
    *args, **kwargs
  File "/usr/lib/python2.6/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib64/python2.6/contextlib.py", line 113, in nested
    yield vars
  File "/usr/lib/python2.6/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/lib/python2.6/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/var/www/vhosts/s19309659.onlinehome-server.com/httpdocs/LRS/ADL_LRS/fabfile.py", line 52, in setup_lrs
    from django.conf import settings
  File "/usr/lib/python2.6/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/usr/lib/python2.6/site-packages/django/utils/version.py", line 7, in <module>
    from django.utils.lru_cache import lru_cache
  File "/usr/lib/python2.6/site-packages/django/utils/lru_cache.py", line 28
    fasttypes = {int, str, frozenset, type(None)},
                    ^
SyntaxError: invalid syntax

Can anyone help to solve it? thanks in advance.

best,
Yuxin

**Comment by ljwolford** [comment]
The LRS runs with python 2.7+....try using one of those versions instead of python2.6. Thank you.

**Comment by Yuxin92** [comment]
Got it. I thought python 2.6+ include 2.6... Thanks a lot. Now I get another problem in last step. I guess I'd better open a new issue.
