### ISSUE TITLE
Not working in the server

### ISSUE THREAD

**Issue by sharifmehdia** [adlnet/ADL_LRS#435]
Hi, I have installed the LRS into my local machine (localhost) and its working great. But when I am trying to install it into my server, then I am getting error and its not working. can you suggest me some way of making it correct? I am getting this error after "source ../env/bin/activate" command. Probably the host issue. Please check/

ubuntu@ip-172-31-30-142:~/ADL_LRS$ source ../env/bin/activate
(env) ubuntu@ip-172-31-30-142:~/ADL_LRS$ fab setup_lrs
[localhost] local: ./manage.py createcachetable
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/management/commands/createcachetable.py", line 41, in handle
    self.create_table(db, cache._table, dry_run)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/management/commands/createcachetable.py", line 49, in create_table
    if tablename in connection.introspection.table_names():
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/db/backends/base/introspection.py", line 56, in table_names
    with self.connection.cursor() as cursor:
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 175, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: could not translate host name "http://tokyo.x-in-y.com/" to address: Name or service not known

Fatal error: local() encountered an error (return code 1) while executing './manage.py createcachetable'

Aborting.
(env) ubuntu@ip-172-31-30-142:~/ADL_LRS$
(env) ubuntu@ip-172-31-30-142:~/ADL_LRS$ Fatal error: local() encountered an error (return code 1) while executing './manage.py createcachetable'

**Comment by ljwolford** [comment]
Did you change your DATABASES setting in settings.py? If your postgres installation is on the same machine as the LRS then you can leave the HOST param as `localhost`. If not you can change HOST to the IP address of the postgres server, then edit the `pg_hba.conf` file in postgres to accept connections from your LRS server. I hope this helps.

**Comment by ljwolford** [comment]
closed due to inactivity
