### ISSUE TITLE
HTTP 409 error

### ISSUE THREAD

**Issue by MrBillMcDonald** [adlnet/ADL_LRS#436]
Lou,

I have just installed the current version and I am getting an HTTP 409 error when writing statements.

The statements do actually get written to the LRS so it is somewhat confusing.

Any ideas ?

**Comment by ljwolford** [comment]
Hi Bill,

The 409 error is a conflict error, meaning the statement that's being submitted has an ID that is already being used by another statement already saved in the LRS. If you do a query with statementId it should only return a single statement. Are you assigning ids to the statements before you send them, or are you leaving them blank and having the LRS assign its own ids?

**Comment by MrBillMcDonald** [comment]
I am  using ADL.XAPIWrapper.sendStatement(stmt) without setting the statement ID.  

I Inspected the stmt Object before and after calling sendStatement().  It had no ID going in but it did have one after the call so sendStatement() did apparently modify it.

FYI -this function did work correctly before with and earlier version of the ADL LRS.

Has ADL.XAPIWrapper.sendStatement() been changed recently ?

**Comment by ljwolford** [comment]
Since the xAPIWrapper is generating the UUID before you send it, can you open an issue here:
https://github.com/adlnet/xAPIWrapper ?

Thanks, I don't believe this is an LRS issue. Try relaunching whatever app is sending the statements. Also try it against the public LRS just to be sure.

**Comment by MrBillMcDonald** [comment]
It works with the public LRS  (https://lrs.adlnet.gov/) so it would appear that it is a problem with my instance of the ADL LRS.  (Not with the client).

**Comment by MrBillMcDonald** [comment]
Here is the **lrs.log** logfile.   (for one statement write attempt).  It appears that there is a socket failure followed by resend which results in a duplicate entry error.


```
ubuntu@ip-172-31-10-50:/home/lrsdbuser/TESTLRS/logs$ cat lrs.log
2016-11-09 15:09:06,888 [INFO] lrs.views:
Exception while processing: /XAPI/statements
2016-11-09 15:09:06,888 [ERROR] lrs.views: [Errno 111] Connection refused
Traceback (most recent call last):
  File "./lrs/views.py", line 219, in handle_request
    return processors[path][req_dict['method']](req_dict)
  File "./lrs/utils/req_process.py", line 131, in statements_post
    check_activity_metadata.delay(stmt_ids)
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/celery/app/task.py", line 559, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/celery/app/base.py", line 353, in send_task
    reply_to=reply_to or self.oid, **options
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/kombu/connection.py", line 382, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/kombu/connection.py", line 250, in connect
    return self.connection
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/kombu/connection.py", line 756, in connection
    self._connection = self._establish_connection()
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/kombu/connection.py", line 711, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/home/lrsdbuser/TESTLRS/env/local/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2016-11-09 15:09:07,003 [INFO] lrs.views:
Exception while processing: /XAPI/statements
2016-11-09 15:09:07,003 [ERROR] lrs.views: A statement with ID 70e50904-2f2c-4d11-a173-e7d51fec6ae9 already exists
Traceback (most recent call last):
  File "./lrs/views.py", line 218, in handle_request
    req_dict = validators[path][r_dict['method']](r_dict)
  File "./lrs/utils/authorization.py", line 34, in inner
    return func(request, *args, **kwargs)
  File "./lrs/utils/req_validate.py", line 105, in statements_post
    validate_body(body, req_dict['auth'], req_dict.get('payload_sha2s', None), req_dict['headers']['CONTENT_TYPE'])
  File "./lrs/utils/req_validate.py", line 69, in validate_body
    [server_validate_statement(stmt, auth, payload_sha2s, content_type) for stmt in body]
  File "./lrs/utils/req_validate.py", line 77, in server_validate_statement
    raise ParamConflict(err_msg)
ParamConflict: A statement with ID 70e50904-2f2c-4d11-a173-e7d51fec6ae9 already exists
ubuntu@ip-172-31-10-50:/home/lrsdbuser/TESTLRS/logs$
```

**Comment by ljwolford** [comment]
Try restarting the celery processes, then check the lrs log and celery logs to make sure they started ok. You can also run `ps aux | grep celery` to make sure they are up and running.

**Comment by MrBillMcDonald** [comment]
Found the problem - I didn't have rabbitmq installed!  Oops!
